### ISSUE TITLE
MIUI Launcher FC

### ISSUE THREAD

**Issue by BenEfrati** [ingbrzy/MIUI-XML-V8-HEBREW#2]
When selecting Hebrew there is fc in miui launcher
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miui.home/com.miui.home.launcher.Launcher}: android.view.InflateException: Binary XML file line #8: Error inflating class com.miui.home.launcher.EditingEntryThumbnailView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
at android.app.ActivityThread.access$800(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
at android.os.Handler.dispatchMessage(Handler.java)
at android.os.Looper.loop(Looper.java)
at android.app.ActivityThread.main(ActivityThread.java)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.miui.home.launcher.EditingEntryThumbnailView
at android.view.LayoutInflater.createView(LayoutInflater.java)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
at android.view.LayoutInflater.rInflate(LayoutInflater.java)
at android.view.LayoutInflater.rInflate(LayoutInflater.java)
at android.view.LayoutInflater.rInflate(LayoutInflater.java)
at android.view.LayoutInflater.parseInclude(LayoutInflater.java)
at android.view.LayoutInflater.rInflate(LayoutInflater.java)
at android.view.LayoutInflater.inflate(LayoutInflater.java)
at android.view.LayoutInflater.inflate(LayoutInflater.java)
at android.view.LayoutInflater.inflate(LayoutInflater.java)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:400)
at android.app.Activity.setContentView(Activity.java)
at com.miui.home.launcher.Launcher.onCreate(Launcher.java)
at android.app.Activity.performCreate(Activity.java)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
... 11 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
... 26 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
at com.miui.home.launcher.EditingEntryThumbnailView.initIconDrawableIds(EditingEntryThumbnailView.java)
at com.miui.home.launcher.EditingEntryThumbnailView.(EditingEntryThumbnailView.java)
at com.miui.home.launcher.EditingEntryThumbnailView.(EditingEntryThumbnailView.java)
... 28 more
```

![image](https://cloud.githubusercontent.com/assets/1887540/21454042/ce798b8a-c91d-11e6-8744-6b0081ad471a.png)

**Comment by IgorEisberg** [comment]
Fixed.
